# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OhVM_lMQfEobVgRb1KByGdQCJkEznt6i
"""

from prometheus_client import start_http_server, Gauge
import pandas as pd
import time

# Cargar datos desde el CSV
df = pd.read_csv("datos_temperatura.csv", parse_dates=["time"])

# Crear métrica tipo Gauge (valor que cambia con el tiempo)
temperatura = Gauge('temperatura_ciudad', 'Temperatura por ciudad', ['ciudad'])

# Función para enviar los datos como métricas
def exportar():
    for _, row in df.iterrows():
        temperatura.labels(ciudad=row['ciudad']).set(row['temperatura'])
        time.sleep(1)  # Simula envío progresivo

# Iniciar servidor en puerto 8000
if __name__ == '__main__':
    start_http_server(8000)
    while True:
        exportar()